version: '3'

services:
  web:
    container_name: 'code_college_web'
    build: .
    volumes:
      - .:/home/CodeCollege
    command: python3 code_college/manage.py runserver 0.0.0.0:8000
    tty: True
    depends_on:
      - migrate
    ports:
      - "8000:8000"

  migrate:
    container_name: 'code_college_migrate'
    build: .
    volumes:
      - .:/home/CodeCollege
    command: python3 code_college/manage.py migrate
    depends_on:
      - migrations
    environment:
      - EMAIL_ADDRESS="somemail@gmail.com"
      - EMAIL_PWD="password"
    tty: True

  migrations:
    container_name: 'code_college_migrations'
    environment:
      - EMAIL_ADDRESS="somemail@gmail.com"
      - EMAIL_PWD="password"
    build: .
    volumes:
      - .:/home/CodeCollege
    command: python3 code_college/manage.py makemigrations
    tty: True
